// data.js — global data for runningnederland.nl

var EVENTS = [
  {
    id: 1,
    name_nl: "Groninger Crossloop",
    name_en: "Groningen Cross Run",
    date: "2026-03-29",
    type: "cross",
    city: "Groningen",
    province: "Groningen",
    distances: ["8km"],
    paid: true,
    price: "€10",
    atletiekunie: true,
    capacity: 300,
    categories: ["Heren", "Dames"],
    organizer: "",
    description_nl: "Een geweldige crossloop door het mooie Groningse landschap. Geniet van de uitdagende paden en sfeervolle omgeving terwijl je strijdt voor de beste tijd.",
    description_en: "A great cross run through the beautiful Groningen landscape. Enjoy the challenging paths and atmospheric surroundings while competing for the best time.",
    image: "https://images.unsplash.com/photo-1571008887538-b36bb32f4571?w=800&q=80",
    registration_url: "#",
    youtube_url: ""
  },
  {
    id: 2,
    name_nl: "Utrecht Studentenloop",
    name_en: "Utrecht Student Run",
    date: "2026-04-04",
    type: "studentenevenement",
    city: "Utrecht",
    province: "Utrecht",
    distances: ["5km", "10km"],
    paid: true,
    price: "€8",
    atletiekunie: false,
    capacity: 600,
    categories: ["Jeugd", "Heren", "Dames"],
    organizer: "",
    description_nl: "De jaarlijkse studentenloop door de historische binnenstad van Utrecht. Perfect voor studenten van alle niveaus.",
    description_en: "The annual student run through the historic city centre of Utrecht. Perfect for students of all levels.",
    image: "https://images.unsplash.com/photo-1517649763962-0c623066013b?w=800&q=80",
    registration_url: "#",
    youtube_url: ""
  },
  {
    id: 3,
    name_nl: "Rotterdam Parkloop",
    name_en: "Rotterdam Park Run",
    date: "2026-04-04",
    type: "parkloop",
    city: "Rotterdam",
    province: "Zuid-Holland",
    distances: ["5km"],
    paid: false,
    price: "gratis",
    atletiekunie: false,
    capacity: 250,
    categories: ["Heren", "Dames"],
    organizer: "",
    description_nl: "Een gratis parkloop in het hart van Rotterdam. Ideaal voor beginners en recreatieve lopers die willen genieten van de mooie parkomgeving.",
    description_en: "A free park run in the heart of Rotterdam. Ideal for beginners and recreational runners who want to enjoy the beautiful park surroundings.",
    image: "https://images.unsplash.com/photo-1552674605-db6ffd4facb5?w=800&q=80",
    registration_url: "#",
    youtube_url: ""
  },
  {
    id: 4,
    name_nl: "Leiden Lenteloop",
    name_en: "Leiden Spring Run",
    date: "2026-04-12",
    type: "wegevenement",
    city: "Leiden",
    province: "Zuid-Holland",
    distances: ["5km", "10km"],
    paid: true,
    price: "€15/€20",
    atletiekunie: true,
    capacity: 800,
    categories: ["Heren", "Dames"],
    organizer: "",
    description_nl: "De Leiden Lenteloop is een prachtig wegloopevents door de historische grachten en straten van Leiden. Een gecertificeerd parcours met tijdregistratie.",
    description_en: "The Leiden Spring Run is a beautiful road running event through the historic canals and streets of Leiden. A certified course with time registration.",
    image: "https://images.unsplash.com/photo-1544899489-a083461b088c?w=800&q=80",
    registration_url: "#",
    youtube_url: ""
  },
  {
    id: 5,
    name_nl: "Virtuele Voorjaarsloop",
    name_en: "Virtual Spring Run",
    date: "2026-04-15",
    type: "virtuele run",
    city: "(online)",
    province: "Noord-Holland",
    distances: ["5km", "10km", "21km"],
    paid: true,
    price: "€15",
    atletiekunie: false,
    capacity: 10000,
    categories: ["Heren", "Dames"],
    organizer: "",
    description_nl: "Loop de Virtuele Voorjaarsloop overal ter wereld! Registreer je tijd en ontvang een exclusieve medaille thuis bezorgd. Lopen wanneer en waar jij wilt.",
    description_en: "Run the Virtual Spring Run anywhere in the world! Register your time and receive an exclusive medal delivered to your home. Run when and where you want.",
    image: "https://images.unsplash.com/photo-1461896836934-ffe607ba8211?w=800&q=80",
    registration_url: "#",
    youtube_url: ""
  },
  {
    id: 6,
    name_nl: "Inclusieve Wandeling Delft",
    name_en: "Inclusive Walk Delft",
    date: "2026-04-19",
    type: "inclusieve runs",
    city: "Delft",
    province: "Zuid-Holland",
    distances: ["5km"],
    paid: false,
    price: "gratis",
    atletiekunie: false,
    capacity: 150,
    categories: ["Aangepast Sporten"],
    organizer: "",
    description_nl: "Een inclusieve wandeling door het mooie Delft, toegankelijk voor iedereen, inclusief mensen met een beperking. Samen bewegen in een veilige omgeving.",
    description_en: "An inclusive walk through beautiful Delft, accessible to everyone, including people with disabilities. Moving together in a safe environment.",
    image: "https://images.unsplash.com/photo-1476480862126-209bfaa8edc8?w=800&q=80",
    registration_url: "#",
    youtube_url: ""
  },
  {
    id: 7,
    name_nl: "Arnhem Sportief Wandelen",
    name_en: "Arnhem Sports Walking",
    date: "2026-04-19",
    type: "sportief wandelen",
    city: "Arnhem",
    province: "Gelderland",
    distances: ["10km", "20km"],
    paid: true,
    price: "€12",
    atletiekunie: false,
    capacity: 400,
    categories: ["Heren", "Dames", "Aangepast Sporten"],
    organizer: "",
    description_nl: "Sportief wandelen door de prachtige Veluwse natuur rondom Arnhem. Geschikt voor wandelaars van alle niveaus en toegankelijk voor deelnemers met een beperking.",
    description_en: "Sports walking through the beautiful Veluwe nature around Arnhem. Suitable for walkers of all levels and accessible for participants with disabilities.",
    image: "https://images.unsplash.com/photo-1593079831268-3381b0db4a77?w=800&q=80",
    registration_url: "#",
    youtube_url: ""
  },
  {
    id: 8,
    name_nl: "Haarlem 10K Klassiek",
    name_en: "Haarlem 10K Classic",
    date: "2026-04-26",
    type: "gecertificeerd parcours",
    city: "Haarlem",
    province: "Noord-Holland",
    distances: ["10km"],
    paid: true,
    price: "€18",
    atletiekunie: true,
    capacity: 2500,
    categories: ["Heren", "Dames"],
    organizer: "",
    description_nl: "Het iconische Haarlem 10K Klassiek op een volledig gecertificeerd parcours door de historische binnenstad. Ideaal voor het neerzetten van een persoonlijk record.",
    description_en: "The iconic Haarlem 10K Classic on a fully certified course through the historic city centre. Ideal for setting a personal record.",
    image: "https://images.unsplash.com/photo-1530143584546-02191bc84eb5?w=800&q=80",
    registration_url: "#",
    youtube_url: ""
  },
  {
    id: 9,
    name_nl: "Eindhoven Kleurenfestival",
    name_en: "Eindhoven Colour Festival",
    date: "2026-04-26",
    type: "funrun",
    city: "Eindhoven",
    province: "Noord-Brabant",
    distances: ["5km"],
    paid: false,
    price: "gratis",
    atletiekunie: false,
    capacity: 1200,
    categories: ["Heren", "Dames", "Jeugd"],
    organizer: "",
    description_nl: "Het meest kleurrijke hardloopevenement van Nederland! Word bedolven onder de kleuren terwijl je loopt door het centrum van Eindhoven. Voor heel de familie!",
    description_en: "The most colourful running event in the Netherlands! Get covered in colours as you run through the centre of Eindhoven. For the whole family!",
    image: "https://images.unsplash.com/photo-1502904550040-7534597429ae?w=800&q=80",
    registration_url: "#",
    youtube_url: ""
  },
  {
    id: 10,
    name_nl: "Zwolle Coopertest",
    name_en: "Zwolle Cooper Test",
    date: "2026-05-02",
    type: "coopertest",
    city: "Zwolle",
    province: "Overijssel",
    distances: ["12min"],
    paid: true,
    price: "€8",
    atletiekunie: true,
    capacity: 100,
    categories: ["Heren", "Dames", "Jeugd"],
    organizer: "",
    description_nl: "De officiële Cooper 12-minutentest in Zwolle. Meet je uithoudingsvermogen en vergelijk je prestaties met normtabellen voor jouw leeftijdsgroep.",
    description_en: "The official Cooper 12-minute test in Zwolle. Measure your endurance and compare your performance with norm tables for your age group.",
    image: "https://images.unsplash.com/photo-1560073743-0a45abee4e02?w=800&q=80",
    registration_url: "#",
    youtube_url: ""
  },
  {
    id: 11,
    name_nl: "Amsterdam Trail Classic",
    name_en: "Amsterdam Trail Classic",
    date: "2026-05-10",
    type: "trail",
    city: "Amsterdam",
    province: "Noord-Holland",
    distances: ["15km", "30km"],
    paid: true,
    price: "€35/€55",
    atletiekunie: false,
    capacity: 400,
    categories: ["Heren", "Dames"],
    organizer: "",
    description_nl: "De Amsterdam Trail Classic neemt je mee door de bosrijke omgeving van het Amsterdamse Bos. Uitdagende routes voor zowel beginnende als ervaren trail runners.",
    description_en: "The Amsterdam Trail Classic takes you through the forested surroundings of the Amsterdam Forest. Challenging routes for both beginner and experienced trail runners.",
    image: "https://images.unsplash.com/photo-1551698618-1dfe5d97d256?w=800&q=80",
    registration_url: "#",
    youtube_url: ""
  },
  {
    id: 12,
    name_nl: "Zeeland Survival Run",
    name_en: "Zeeland Survival Run",
    date: "2026-05-16",
    type: "survivalrun",
    city: "Middelburg",
    province: "Zeeland",
    distances: ["8km"],
    paid: true,
    price: "€25",
    atletiekunie: false,
    capacity: 250,
    categories: ["Heren", "Dames"],
    organizer: "",
    description_nl: "Test je grenzen bij de Zeeland Survival Run! Klim over obstakels, kruip door modder en bewijs dat jij de uitdaging aankunt in het mooie Zeeuwse landschap.",
    description_en: "Test your limits at the Zeeland Survival Run! Climb over obstacles, crawl through mud and prove you can handle the challenge in the beautiful Zeeland landscape.",
    image: "https://images.unsplash.com/photo-1434682881908-b43d0467b798?w=800&q=80",
    registration_url: "#",
    youtube_url: ""
  },
  {
    id: 13,
    name_nl: "Maastricht Marathon",
    name_en: "Maastricht Marathon",
    date: "2026-05-17",
    type: "marathon",
    city: "Maastricht",
    province: "Limburg",
    distances: ["10km", "21km", "42km"],
    paid: true,
    price: "€25/€45/€75",
    atletiekunie: true,
    capacity: 5000,
    categories: ["Heren", "Dames"],
    organizer: "",
    description_nl: "De Maastricht Marathon is een van de meest geliefde marathons van Nederland. Loop door de schilderachtige straten van Maastricht langs historische monumenten en door het Limburgse heuvelland.",
    description_en: "The Maastricht Marathon is one of the most beloved marathons in the Netherlands. Run through the picturesque streets of Maastricht past historical monuments and through the Limburg hill country.",
    image: "https://images.unsplash.com/photo-1596727362302-b8d891c42ab8?w=800&q=80",
    registration_url: "#",
    youtube_url: "https://www.youtube.com/watch?v=dQw4w9WgXcQ"
  },
  {
    id: 14,
    name_nl: "Den Haag Estafette",
    name_en: "The Hague Relay",
    date: "2026-05-24",
    type: "estafette",
    city: "Den Haag",
    province: "Zuid-Holland",
    distances: ["4×5km"],
    paid: true,
    price: "€20pp",
    atletiekunie: false,
    capacity: 1000,
    categories: ["Heren", "Dames", "Business Run"],
    organizer: "",
    description_nl: "Loop samen de Den Haag Estafette! Vorm een team van 4 personen en loop elk een etappe van 5km door het hart van Den Haag. Geweldig voor bedrijfsteams!",
    description_en: "Run the Den Haag Relay together! Form a team of 4 and each run a 5km leg through the heart of The Hague. Great for company teams!",
    image: "https://images.unsplash.com/photo-1533560904424-a0c61dc306fc?w=800&q=80",
    registration_url: "#",
    youtube_url: ""
  },
  {
    id: 15,
    name_nl: "Drenthe Trail Run",
    name_en: "Drenthe Trail Run",
    date: "2026-05-31",
    type: "trail",
    city: "Assen",
    province: "Drenthe",
    distances: ["20km"],
    paid: true,
    price: "€30",
    atletiekunie: false,
    capacity: 300,
    categories: ["Heren", "Dames"],
    organizer: "",
    description_nl: "De Drenthe Trail Run voert je door de prachtige Drentse heide en bossen. Een unieke kans om de wilde natuur van Drenthe te ontdekken op loopschoenen.",
    description_en: "The Drenthe Trail Run takes you through the beautiful Drenthe heathlands and forests. A unique opportunity to discover the wild nature of Drenthe on running shoes.",
    image: "https://images.unsplash.com/photo-1470770903676-69b98201ea1c?w=800&q=80",
    registration_url: "#",
    youtube_url: ""
  },
  {
    id: 16,
    name_nl: "Nijmeegse Nachtloop",
    name_en: "Nijmegen Night Run",
    date: "2026-06-07",
    type: "wegevenement",
    city: "Nijmegen",
    province: "Gelderland",
    distances: ["10km", "15km"],
    paid: true,
    price: "€22/€28",
    atletiekunie: false,
    capacity: 1500,
    categories: ["Heren", "Dames"],
    organizer: "",
    description_nl: "Ervaar de magie van het lopen bij nacht door de verlichte straten van Nijmegen. Een spectaculair evenement met sfeervolle verlichting langs het parcours.",
    description_en: "Experience the magic of running at night through the illuminated streets of Nijmegen. A spectacular event with atmospheric lighting along the course.",
    image: "https://images.unsplash.com/photo-1504025468847-0e438279542c?w=800&q=80",
    registration_url: "#",
    youtube_url: ""
  },
  {
    id: 17,
    name_nl: "Friesland Ultrarun",
    name_en: "Friesland Ultra Run",
    date: "2026-06-14",
    type: "ultrarun",
    city: "Leeuwarden",
    province: "Friesland",
    distances: ["50km", "100km"],
    paid: true,
    price: "€60/€90",
    atletiekunie: false,
    capacity: 200,
    categories: ["Heren", "Dames"],
    organizer: "",
    description_nl: "De ultieme uitdaging voor doorgewinterde lopers: de Friesland Ultrarun. Loop door het unieke Friese polderlandschap over afstanden van 50 of 100 kilometer.",
    description_en: "The ultimate challenge for seasoned runners: the Friesland Ultra Run. Run through the unique Frisian polder landscape over distances of 50 or 100 kilometres.",
    image: "https://images.unsplash.com/photo-1508700115892-45ecd05ae2ad?w=800&q=80",
    registration_url: "#",
    youtube_url: ""
  },
  {
    id: 18,
    name_nl: "Rotterdam Business Run",
    name_en: "Rotterdam Business Run",
    date: "2026-06-18",
    type: "wegevenement",
    city: "Rotterdam",
    province: "Zuid-Holland",
    distances: ["5km"],
    paid: true,
    price: "€35",
    atletiekunie: false,
    capacity: 2000,
    categories: ["Business Run"],
    organizer: "",
    description_nl: "De Rotterdam Business Run is hét netwerkevenement voor bedrijven in de regio Rotterdam. Loop 5km met je collega's en maak indruk op relaties en partners.",
    description_en: "The Rotterdam Business Run is the networking event for companies in the Rotterdam region. Run 5km with your colleagues and impress relations and partners.",
    image: "https://images.unsplash.com/photo-1486218119243-13883505764c?w=800&q=80",
    registration_url: "#",
    youtube_url: ""
  },
  {
    id: 19,
    name_nl: "Almere Parkloop Special",
    name_en: "Almere Park Run Special",
    date: "2026-06-20",
    type: "parkloop",
    city: "Almere",
    province: "Flevoland",
    distances: ["5km"],
    paid: false,
    price: "gratis",
    atletiekunie: false,
    capacity: 300,
    categories: ["Heren", "Dames"],
    organizer: "",
    description_nl: "De Almere Parkloop Special is een gratis hardloopevenement in het groene hart van Almere. Gezellig en toegankelijk voor iedereen die van lopen houdt.",
    description_en: "The Almere Park Run Special is a free running event in the green heart of Almere. Fun and accessible for everyone who loves running.",
    image: "https://images.unsplash.com/photo-1513593771513-7b58b6c4af38?w=800&q=80",
    registration_url: "#",
    youtube_url: ""
  }
];

// Dutch postal code prefixes mapped to {lat, lng}
var POSTAL_CODES = {
  "1000": { lat: 52.3676, lng: 4.9041 },   // Amsterdam
  "2500": { lat: 52.0705, lng: 4.3007 },   // Den Haag
  "3000": { lat: 51.9225, lng: 4.4792 },   // Rotterdam
  "3500": { lat: 52.0907, lng: 5.1214 },   // Utrecht
  "9700": { lat: 53.2194, lng: 6.5665 },   // Groningen
  "5600": { lat: 51.4416, lng: 5.4697 },   // Eindhoven
  "8000": { lat: 52.5168, lng: 6.0830 },   // Zwolle
  "2000": { lat: 52.3874, lng: 4.6462 },   // Haarlem
  "2600": { lat: 52.0116, lng: 4.3571 },   // Delft
  "6800": { lat: 51.9851, lng: 5.8987 },   // Arnhem
  "4300": { lat: 51.4988, lng: 3.6136 },   // Middelburg
  "6200": { lat: 50.8514, lng: 5.6910 },   // Maastricht
  "2700": { lat: 52.0579, lng: 4.4938 },   // Zoetermeer
  "9400": { lat: 52.9926, lng: 6.5611 },   // Assen
  "8900": { lat: 53.2012, lng: 5.7999 },   // Leeuwarden
  "6500": { lat: 51.8126, lng: 5.8372 },   // Nijmegen
  "1300": { lat: 52.3508, lng: 5.2647 },   // Almere
  "2300": { lat: 52.1601, lng: 4.4970 },   // Leiden
  "7500": { lat: 52.2215, lng: 6.8937 },   // Enschede
  "6700": { lat: 51.9693, lng: 5.6660 }    // Wageningen
};

// Haversine distance formula
function haversineKm(lat1, lon1, lat2, lon2) {
  var R = 6371;
  var dLat = (lat2 - lat1) * Math.PI / 180;
  var dLon = (lon2 - lon1) * Math.PI / 180;
  var a =
    Math.sin(dLat / 2) * Math.sin(dLat / 2) +
    Math.cos(lat1 * Math.PI / 180) * Math.cos(lat2 * Math.PI / 180) *
    Math.sin(dLon / 2) * Math.sin(dLon / 2);
  var c = 2 * Math.atan2(Math.sqrt(a), Math.sqrt(1 - a));
  return R * c;
}
